'use client'
import { useState } from 'react'
import { ArrowRight, BookOpen, Check, ChevronDown, Clock3, Menu, Plus, Search, Star, X } from 'lucide-react'

const stages = [
  ['Mise en place', ['Butter an 8×8-in pan', 'Preheat oven to 350°F (170°C)'], 'prep'],
  ['Melt', ['4 oz (115 g) unsalted butter'], 'melt'],
  ['Mix', ['1 cup (200 g) sugar', '¼ tsp vanilla extract', '1 shot fresh espresso', '2 large eggs'], 'mix'],
  ['Fold in', ['½ cup all-purpose flour', '⅓ cup cocoa powder', '¼ tsp baking soda', '¼ tsp table salt'], 'fold'],
  ['Bake', ['350°F (170°C)', '30 to 40 min'], 'bake'],
] as const
const recipes = [
  { name: 'Espresso brownies', tag: 'Sweet · 45 min', tone: 'brown', detail: 'Chocolate · 12 pieces' },
  { name: 'Jollof rice', tag: 'Comfort · 1 hr 15 min', tone: 'red', detail: 'West African · 6 servings' },
  { name: 'Amala & ewedu', tag: 'Classic · 50 min', tone: 'gold', detail: 'Yoruba table · 4 servings' },
  { name: 'Green goddess dressing', tag: 'Fresh · 15 min', tone: 'green', detail: 'Herbs · 1 jar' },
  { name: 'Coconut rice', tag: 'Simple · 35 min', tone: 'cream', detail: 'Weeknight · 4 servings' },
  { name: 'Suya spice mix', tag: 'Pantry · 10 min', tone: 'orange', detail: 'Grill night · 1 jar' },
]

export default function Page() {
  const [app, setApp] = useState(false); const [auth, setAuth] = useState(false); const [menu, setMenu] = useState(false); const [saved, setSaved] = useState(false); const [selected, setSelected] = useState(0); const [heroRecipe, setHeroRecipe] = useState(0)
  if (app) return <AppView saved={saved} setSaved={setSaved} selected={selected} setSelected={setSelected} back={() => setApp(false)} />
  return <main className="site-shell"><header className="nav-wrap"><a className="wordmark" href="#top"><span className="mark">m</span> mise</a><nav className={menu ? 'nav-links open' : 'nav-links'}><a href="#why">Why mise</a><a href="#plans">Plans</a><button className="nav-login" onClick={() => setAuth(true)}>Sign in</button><button className="button button-dark" onClick={() => setAuth(true)}>Start cooking <ArrowRight size={15}/></button></nav><button className="mobile-menu" onClick={() => setMenu(!menu)} aria-label="Menu">{menu ? <X/> : <Menu/>}</button></header>
  <section className="hero" id="top"><div><div className="eyebrow"><span className="eyebrow-dot"/> Your kitchen, made clear</div><h1>Recipes that read<br/><em>like a conversation.</em></h1><p className="hero-text">mise turns scattered recipes into a calm, visual workspace—so you can cook with confidence, teach with clarity, and make food feel good again.</p><div className="hero-actions"><button className="button button-dark" onClick={() => setAuth(true)}>Build your recipe box <ArrowRight size={16}/></button><a className="text-link" href="#why">See how it works <ChevronDown size={15}/></a></div><div className="social-proof"><div className="avatar-stack"><span>J</span><span>A</span><span>M</span><span>+</span></div>Join 2,400+ curious cooks</div></div><div className="hero-art"><div className="art-note note-top"><span className="pin"/> a better way<br/>to see a recipe</div><button className="mini-flow" onClick={() => setHeroRecipe((heroRecipe + 1) % 3)} aria-label="Show another recipe preview"><div className="mini-head">{['Espresso brownies','Jollof rice','Amala & ewedu'][heroRecipe]}<small>{['45 min · 12 pieces','1 hr 15 min · 6 servings','50 min · 4 servings'][heroRecipe]}</small></div><div className="mini-grid"><div className="mini-ingredients"><b>ingredients</b><span>butter</span><span>sugar</span><span>cocoa</span><span>eggs</span><span>flour</span></div><div className="mini-step"><b>melt</b><i/><span>butter</span></div><div className="mini-step"><b>mix</b><i/><span>sweeten</span></div><div className="mini-step"><b>fold</b><i/><span>combine</span></div><div className="mini-step last"><b>bake</b><strong>350°</strong><span>30–40 min</span></div></div><div className="mini-foot">made by <b>{heroRecipe === 0 ? 'Amara K.' : heroRecipe === 1 ? 'Bisi A.' : 'Tunde O.'}</b><span>tap card to switch <Star size={13}/></span></div></button><div className="art-note note-bottom"><span className="line"/> from ingredient<br/>to instinct</div></div></section>
  <section className="statement" id="why"><div className="section-kicker">The idea</div><h2>Good food starts with<br/><em>less friction.</em></h2><p>Recipes should teach you something. Not make you hunt through a group chat, zoom into a screenshot, or guess what “mix well” means.</p></section><section className="feature-band"><div><div className="section-kicker">One place for all your ways of cooking</div><h2>Keep the recipe.<br/><em>Grow the ritual.</em></h2></div><div className="feature-list"><Feature title="Your recipe box" text="Save family classics, chef notes, and the screenshot you keep meaning to organize."/><Feature title="Learn by doing" text="See the why behind each step. Build confidence, one small win at a time."/><Feature title="Plan what matters" text="Turn your recipes into gentle meal plans for your week, family, or goals."/></div></section><section className="plans" id="plans"><div><div className="section-kicker">Simple by design</div><h2>Start free.<br/><em>Go deeper when ready.</em></h2><p>Premium is for people who want a little more structure around the table.</p></div><div className="price-grid"><Price name="The pantry" price="Free" items={['Save up to 20 recipes','Visual recipe flows','Private recipe box']}/><Price name="The table" price="$8" premium items={['Unlimited recipes & collections','Personal meal plans','Family profiles & preferences','Nutrition notes and exports']}/></div></section><footer><a className="wordmark" href="#top"><span className="mark">m</span> mise</a><span>Recipes for the way you actually live.</span><span>© 2026 mise</span></footer>{auth && <Auth close={() => setAuth(false)} explore={() => {setAuth(false);setApp(true)}}/>}</main>
}
function Feature({title,text}:{title:string;text:string}){return <div className="feature"><div className="feature-icon"><Check size={16}/></div><div><h3>{title}</h3><p>{text}</p></div></div>}
function Price({name,price,items,premium}:{name:string;price:string;items:string[];premium?:boolean}){return <div className={premium?'price-card premium':'price-card'}>{premium&&<span className="popular">Most loved</span>}<div className="price-top">{name}<Star size={15}/></div><div className="price">{price}{price!=='Free'&&<small>/ month</small>}</div><ul>{items.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><button className={premium?'button button-dark full':'button button-light full'}>{premium?'Try The table':'Begin for free'} <ArrowRight size={15}/></button></div>}
function Auth({close,explore}:{close:()=>void;explore:()=>void}){return <div className="modal-backdrop" onClick={close}><section className="auth-modal" onClick={e=>e.stopPropagation()}><button className="close-modal" onClick={close} aria-label="Close"><X size={18}/></button><div className="auth-brand"><span className="mark">m</span></div><div className="section-kicker">Welcome to mise</div><h2>Make room for good food.</h2><p className="auth-sub">Your personal recipe box is a few clicks away.</p><button className="google-button"><b className="google-g">G</b> Continue with Google</button><div className="or">or use email</div><label>Email<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="At least 8 characters"/></label><button className="button button-dark full" onClick={explore}>Create my recipe box <ArrowRight size={15}/></button><button className="explore-link" onClick={explore}>Continue exploring without an account</button></section></div>}
function AppView({saved,setSaved,selected,setSelected,back}:{saved:boolean;setSaved:(v:boolean)=>void;selected:number;setSelected:(v:number)=>void;back:()=>void}){return <main className="app-shell"><aside className="app-sidebar"><a className="wordmark" href="#" onClick={back}><span className="mark">m</span> mise</a><div className="sidebar-label">Your kitchen</div><button className="side-link active"><BookOpen size={16}/> Recipe box <span>12</span></button><button className="side-link"><Clock3 size={16}/> This week</button><button className="side-link"><Star size={16}/> Saved</button><div className="sidebar-label space-top">Collections</div><button className="side-link">Sunday suppers</button><button className="side-link">Sweet things</button><div className="profile"><span className="profile-avatar">A</span><div><b>Amara</b><small>Free plan</small></div></div></aside><section className="app-content"><header className="app-header"><div><p className="breadcrumb">Recipe box / Your collection</p><h1>A little something good</h1></div><button className="button button-dark" onClick={()=>setSaved(!saved)}><Plus size={15}/> {saved?'Saved':'Add recipe'}</button></header><div className="app-tabs"><button className="tab active">All recipes <span>12</span></button><button className="tab">Recently added</button><button className="tab">Collections</button><label className="search"><Search size={15}/><input placeholder="Search recipes"/></label></div><div className="recipe-cards">{recipes.map((r,i)=><button className={selected===i?'recipe-card selected':'recipe-card'} key={r.name} onClick={()=>setSelected(i)}><div className={'recipe-image '+r.tone}><span>{r.name}</span></div><div className="recipe-card-info"><h3>{r.name}</h3><p>{r.tag}</p><small>{r.detail}</small><span className="recipe-arrow">{selected===i?'Open recipe':'View'} <ArrowRight size={14}/></span></div></button>)}</div><div className="flow-section"><div className="flow-header"><div><div className="section-kicker">Your visual recipe</div><h2>{recipes[selected].name}</h2></div><button className="save-button" onClick={()=>setSaved(!saved)}><Star size={16}/> {saved?'Saved to box':'Save recipe'}</button></div><div className="flow-scroll"><div className="flow-grid">{stages.map(([label,rows,action])=><div className={'flow-column '+label.toLowerCase().replace(' ','-')} key={label}><div className="flow-label">{label}</div><div className="flow-rows">{rows.map(row=><div className="flow-row" key={row}>{row}</div>)}</div><div className="flow-action">{action}</div></div>)}</div></div></div></section></main>}
